; Generated by prepare_microsoft_terms.py --write; do not edit.
#define MicrosoftTermsRevision "2026-09-22"
#define MicrosoftTermsHashDE "823b247ff9ebeb1c60a9a655a59392213a8fa312a25960e69b3f9e9384d74ed0"
#define MicrosoftTermsHashEN "0f3940fa194892db76725dd62898b95f9763fe1095494ec6f02cbff33e7fc27a"
