; Generated by prepare_microsoft_terms.py --write; do not edit.
#define MicrosoftTermsRevision "2026-09-22"
#define MicrosoftTermsHashDE "f7172696bb38c3632e2a3e6caf74e33d775e3b759533e74e9c902a29c4b84a92"
#define MicrosoftTermsHashEN "20cc1fab0e7543b8d8d2bbc16f1bddd5c571e7fbd534b038364fa8a77cb95174"
