"""Generate/check the complete offline Microsoft recipient agreement; no downloads."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVISION = "2026-09-22"
SPEECH = ("third_party/licenses/python/azure-cognitiveservices-speech/"
          "azure_cognitiveservices_speech-1.51.2.dist-info/licenses/licensefiles/speech/LICENSE.md")
TERMS = [
    ("A. Microsoft Cognitive Services Speech SDK 1.51.2", SPEECH, "cp1252"),
    ("B. Microsoft Visual C++ V14 / 2026 Runtime (14.50)",
     "third_party/upstream/msvc/vc2026-license.txt", "utf-8"),
    ("C. Microsoft Visual C++ 2015-2022 Runtime (14.42 / 14.40)",
     "third_party/upstream/msvc/vc2022-license.txt", "utf-8"),
]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def rtf_escape(text):
    out = []
    for char in text:
        code = ord(char)
        if char in "\\{}":
            out.append("\\" + char)
        elif code > 127:
            # RTF Unicode escapes are signed UTF-16 code units, not code points.
            raw = char.encode("utf-16-le")
            for start in range(0, len(raw), 2):
                unit = int.from_bytes(raw[start:start + 2], "little", signed=True)
                out.append(f"\\u{unit}?")
        else:
            out.append(char)
    return "".join(out)


def render_rtf(sections):
    result = [r"{\rtf1\ansi\ansicpg1252\deff0\uc1{\fonttbl{\f0 Segoe UI;}}"]
    for index, (title, text) in enumerate(sections):
        if index:
            result.append(r"\pard\sa200\par")
        result.append(r"\pard\f0\fs24\b\sa160 " + rtf_escape(title) + r"\b0\par")
        for paragraph in text.splitlines():
            # Preserve every character in the source text, including headings,
            # French regional clauses and the SDK's Markdown notation.
            result.append(r"\pard\f0\fs20\sa100 " + rtf_escape(paragraph) + r"\par")
    result.append("}")
    return ("\n".join(result) + "\n").encode("ascii")


def expected_files(root=ROOT):
    terms = [(title, (root / path).read_text(encoding=encoding))
             for title, path, encoding in TERMS]
    sources = {path: digest((root / path).read_bytes()) for _, path, _ in TERMS}
    output = {}
    hashes = {}
    for lang in ("de", "en"):
        cover_path = f"packaging/licenses/microsoft-components.{lang}.txt"
        cover = (root / cover_path).read_text(encoding="utf-8")
        sources[cover_path] = digest((root / cover_path).read_bytes())
        title, _, body = cover.partition("\n")
        sections = [(title, body.lstrip("\n"))] + terms
        packet = render_rtf(sections)
        path = f"third_party/microsoft-consent/microsoft-components.{lang}.rtf"
        output[path] = packet
        hashes[lang] = digest(packet)
    output["third_party/microsoft-consent/packet.json"] = (
        json.dumps({"revision": REVISION, "sources": sources, "rtf_sha256": hashes}, indent=2) + "\n"
    ).encode()
    output["packaging/licenses/microsoft-terms.iss"] = (
        "; Generated by prepare_microsoft_terms.py --write; do not edit.\n"
        f'#define MicrosoftTermsRevision "{REVISION}"\n'
        f'#define MicrosoftTermsHashDE "{hashes["de"]}"\n'
        f'#define MicrosoftTermsHashEN "{hashes["en"]}"\n'
    ).encode()
    return output


def prepare(root=ROOT, *, write=False):
    output = expected_files(root)
    for relative, expected in output.items():
        target = root / relative
        if write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(expected)
        elif not target.is_file() or target.read_bytes() != expected:
            raise ValueError(f"Missing/stale Microsoft agreement: {relative}. "
                             "Review the terms, run prepare_microsoft_terms.py --write "
                             "and refresh the third-party manifest.")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    prepare(write=args.write)
    print("Microsoft agreement generated." if args.write else "Microsoft agreement verified.")
